name: webview_flutter
description: A Fork from webview_flutter.
version: 0.3.19+8
homepage: https://github.com/sangvu0909/plugins/tree/master/packages/webview_flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
      ios:
        pluginClass: FLTWebViewFlutterPlugin
